import 'tailwindcss/tailwind.css';

export const metadata = {
  title: 'It\'s a Date <3',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className='text-center px-8 py-14 font-mono w-screen h-screen overflow-hidden bg-gray-50 text-gray-900'>
        <header className='flex align-middle justify-center'>
          <h1 className='text-3xl'>It&apos;s a Date 💜</h1>
        </header>
        {children}
        <footer className='absolute bottom-5 w-full flex justify-center text-gray-300'>feito com s2 por&nbsp; 
          <a className='italic text-purple-300 hover:cursor-pointer hover:text-purple-400 transition-colors' target='_blank' href="https://github.com/thiagowaib">thigas</a>
        </footer>
      </body>
    </html>
  )
}
